### PR TITLE
fix race condition when loading volumes concurrently

### LINKED ISSUE #1682: panic when loading volumes concurrently
**Describe the bug**
Loading same volume more than once leads to SIGSEGV

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

1. start server: `./weed server`
2. upload some random files
3. restart with "-volume.index leveldb"
 `./weed server -volume.index leveldb`

4. crash log

> I1216 18:24:45 91019 master_grpc_server.go:250] + client master@10.170.160.252:56816
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb
I1216 18:24:45 91019 volume_loading.go:128] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/4.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/2.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/3.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/1.ldb error: resource temporarily unavailable
I1216 18:24:45 91019 volume_loading.go:135] loading leveldb /var/folders/1x/lbz9zhkd1_n0vd2zlmsl_0n40000gn/T/5.ldb error: resource temporarily unavailable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x49e80be]

**Expected behavior**
not crash

### PR DESCRIPTION
**Pull request by qieqieplus**
fix #1682

### CODE REVIEW

File: weed/storage/disk_location.go [hunk 1]
```diff
@@ -99,12 +99,14 @@ func (l *DiskLocation) loadExistingVolume(fileInfo os.FileInfo, needleMapKind Ne
...
-	_, found := l.volumes[vid]
-	l.volumesLock.RUnlock()
-	if found {
+	l.volumesLock.Lock()
+	if _, found := l.volumes[vid]; found {
+		l.volumesLock.Unlock()
 		glog.V(1).Infof("loaded volume, %v", vid)
 		return true
+	} else {
+		l.volumes[vid] = nil
```
Comment (chrislusf) [inline weed/storage/disk_location.go:108]: Should just delete it?

**Review by chrislusf — COMMENTED** [review]
There should not be a case where one volume is being loaded twice at the same time. Need to fix the original problem instead of there.

This PR is not fixing the right problem. I am going to revert this PR.

File: weed/storage/disk_location.go (hunk 1 above)
Comment (qieqieplus) [reply weed/storage/disk_location.go:108]: Generally the get-or-create process should be atomic, so you have to hold the lock until SetVolume is done.
Put placeholder nil in volumes allows you unlock earlier and don't have to wait for `NewVolume`, `SetVolume`
